services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: arc-backend-app:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      JWT_KEY: ${JWT_KEY}
      FRONTEND_HOSTS: ${FRONTEND_HOSTS}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      GMAIL: ${GMAIL}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  redis:
    image: redis:8.6.2
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    restart: unless-stopped
  nginx:
    image: nginx:1.28.3
    environment:
      DOMAIN: ${DOMAIN}
      FASTAPI_HOST: app:8000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/log:/var/log/nginx
      - ./nginx:/etc/nginx/templates:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - app
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    depends_on:
      - nginx
    entrypoint: >
      sh -c "while true; do certbot renew --non-interactive --webroot -w /var/www/certbot --quiet; sleep 12h; done"

volumes:
  db_data:
  certbot-etc:
  certbot-var: