services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  app:
    build: ./app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      JWT_KEY: ${JWT_KEY}
      FRONTEND_HOSTS: ${FRONTEND_HOSTS}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      GMAIL: ${GMAIL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      HMAC_KEY: ${HMAC_KEY}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      INTERNAL_ROUTE: ${INTERNAL_ROUTE}
    depends_on:
      ai_analyst:
        condition: service_started
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
  redis:
    image: redis:8.6.2
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
  nginx:
    image: nginx:1.28.3
    environment:
      DOMAIN: ${DOMAIN}
      FASTAPI_HOST: app:8000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/log:/var/log/nginx
      - ./nginx:/etc/nginx/templates:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - app
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
    depends_on:
      - nginx
    entrypoint: >
      sh -c "while true; do certbot renew --non-interactive --webroot -w /var/www/certbot --quiet; sleep 12h; done"
  ai_analyst:
    build: ./ai_analyst
    command: uv run --no-sync uvicorn src.main:app --host 0.0.0.0 --port 8001
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  worker:
    build: ./ai_analyst
    command: uv run --no-sync celery -A src.queue.celery_app worker --loglevel=info
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      INTERNAL_ROUTE: ${INTERNAL_ROUTE}
    depends_on:
      rabbitmq:
        condition: service_healthy
      app:
        condition: service_started
    restart: unless-stopped
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio_init:
    image: quay.io/minio/minio
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_BUCKET_NAME=${S3_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
        mc mb --ignore-existing local/$${MINIO_BUCKET_NAME}
      "

volumes:
  db_data:
  certbot-etc:
  certbot-var:
  rabbitmq_data:
  minio_data: