"""unique bookmark fields

Revision ID: 033b0fc97894
Revises: c930921c5a6c
Create Date: 2026-08-01 10:31:04.883821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033b0fc97894'
down_revision: Union[str, Sequence[str], None] = 'c930921c5a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_analysis_bookmark_user_type_analysis', 'analysis_bookmarks', ['user_id', 'analysis_type', 'analysis_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_analysis_bookmark_user_type_analysis', 'analysis_bookmarks', type_='unique')
    # ### end Alembic commands ###
