"""add reservations id connection with analysis

Revision ID: 0473e8ec2dfa
Revises: 3d13f7cbcd97
Create Date: 2026-09-30 14:08:16.786711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0473e8ec2dfa'
down_revision: Union[str, Sequence[str], None] = '3d13f7cbcd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comprehensive_analyses', sa.Column('reservation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_comprehensive_analyses_reservation_id'), 'comprehensive_analyses', ['reservation_id'], unique=False)
    op.create_foreign_key('comprehensive_analyses_reservation_id_fkey', 'comprehensive_analyses', 'credit_reservations', ['reservation_id'], ['id'])
    op.add_column('cover_letters', sa.Column('reservation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cover_letters_reservation_id'), 'cover_letters', ['reservation_id'], unique=False)
    op.create_foreign_key('cover_letters_reservation_id_fkey', 'cover_letters', 'credit_reservations', ['reservation_id'], ['id'])
    op.add_column('keyword_analyses', sa.Column('reservation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_keyword_analyses_reservation_id'), 'keyword_analyses', ['reservation_id'], unique=False)
    op.create_foreign_key('keyword_analyses_reservation_id_fkey', 'keyword_analyses', 'credit_reservations', ['reservation_id'], ['id'])
    op.add_column('resume', sa.Column('reservation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_resume_reservation_id'), 'resume', ['reservation_id'], unique=False)
    op.create_foreign_key('resume_reservation_id_fkey', 'resume', 'credit_reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resume_reservation_id_fkey', 'resume', type_='foreignkey')
    op.drop_index(op.f('ix_resume_reservation_id'), table_name='resume')
    op.drop_column('resume', 'reservation_id')
    op.drop_constraint('keyword_analyses_reservation_id_fkey', 'keyword_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_keyword_analyses_reservation_id'), table_name='keyword_analyses')
    op.drop_column('keyword_analyses', 'reservation_id')
    op.drop_constraint('cover_letters_reservation_id_fkey', 'cover_letters', type_='foreignkey')
    op.drop_index(op.f('ix_cover_letters_reservation_id'), table_name='cover_letters')
    op.drop_column('cover_letters', 'reservation_id')
    op.drop_constraint('comprehensive_analyses_reservation_id_fkey', 'comprehensive_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_comprehensive_analyses_reservation_id'), table_name='comprehensive_analyses')
    op.drop_column('comprehensive_analyses', 'reservation_id')
    # ### end Alembic commands ###
