"""add metadata to credit_reservations

Revision ID: 1640a4040ee2
Revises: 0473e8ec2dfa
Create Date: 2026-10-03 10:09:12.157771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1640a4040ee2'
down_revision: Union[str, Sequence[str], None] = '0473e8ec2dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_reservations', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_reservations', 'meta_data')
    # ### end Alembic commands ###
