"""add reservations id connection with individual analysis

Revision ID: 1a9d0fc41de9
Revises: 1640a4040ee2
Create Date: 2026-10-05 08:08:44.720532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9d0fc41de9'
down_revision: Union[str, Sequence[str], None] = '1640a4040ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_analyses', sa.Column('reservation_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_individual_analyses_reservation_id'), 'individual_analyses', ['reservation_id'], unique=False)
    op.create_foreign_key('fk_individual_analyses_reservation_id', 'individual_analyses', 'credit_reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_individual_analyses_reservation_id', 'individual_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_individual_analyses_reservation_id'), table_name='individual_analyses')
    op.drop_column('individual_analyses', 'reservation_id')
    # ### end Alembic commands ###
