"""add timestamps to analyses and resume

Revision ID: 21ce4ac105a2
Revises: bf7dc70d2e2b
Create Date: 2026-06-11 00:33:43.530705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce4ac105a2'
down_revision: Union[str, Sequence[str], None] = 'bf7dc70d2e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comprehensive_analyses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('comprehensive_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('individual_analyses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('individual_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('keyword_analyses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('keyword_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resume', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resume', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'updated_at')
    op.drop_column('resume', 'created_at')
    op.drop_column('keyword_analyses', 'updated_at')
    op.drop_column('keyword_analyses', 'created_at')
    op.drop_column('individual_analyses', 'updated_at')
    op.drop_column('individual_analyses', 'created_at')
    op.drop_column('comprehensive_analyses', 'updated_at')
    op.drop_column('comprehensive_analyses', 'created_at')
    # ### end Alembic commands ###
