"""add language, title field to resume table

Revision ID: 26271fa5752d
Revises: f2745010aa55
Create Date: 2026-07-18 02:40:07.807731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26271fa5752d'
down_revision: Union[str, Sequence[str], None] = 'f2745010aa55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = sa.Enum('ko', 'en', name='language')
    language_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('resume', sa.Column('language', language_enum, nullable=True))
    op.execute("UPDATE resume SET language = 'ko' WHERE language IS NULL")
    op.alter_column('resume', 'language', nullable=False)
    op.add_column('resume', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'title')
    op.drop_column('resume', 'language')
    sa.Enum(name='language').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
