"""add query_params, optional target_user_id to audit_logs

Revision ID: 274313a4d219
Revises: ec6c3d196ce9
Create Date: 2026-08-03 16:29:24.238151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '274313a4d219'
down_revision: Union[str, Sequence[str], None] = 'ec6c3d196ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'target_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'target_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('audit_logs', 'query_params')
    # ### end Alembic commands ###
