"""add credit tables

Revision ID: 3d13f7cbcd97
Revises: 65d8358741aa
Create Date: 2026-09-30 07:48:40.631093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d13f7cbcd97'
down_revision: Union[str, Sequence[str], None] = '65d8358741aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


credit_reservation_status = postgresql.ENUM(
    'RESERVED', 'CAPTURED', 'RELEASED',
    name='creditreservationstatus',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    credit_reservation_status.create(op.get_bind(), checkfirst=True)
    op.create_table('credit_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledgers_created_at'), 'credit_ledgers', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_ledgers_idempotency_key'), 'credit_ledgers', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_credit_ledgers_reference_id'), 'credit_ledgers', ['reference_id'], unique=False)
    op.create_index(op.f('ix_credit_ledgers_reference_type'), 'credit_ledgers', ['reference_type'], unique=False)
    op.create_index(op.f('ix_credit_ledgers_user_id'), 'credit_ledgers', ['user_id'], unique=False)
    op.create_table('credit_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', credit_reservation_status, nullable=False),
    sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='chk_positive_reservation_amount'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_reservations_idempotency_key'), 'credit_reservations', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_credit_reservations_status'), 'credit_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_credit_reservations_user_id'), 'credit_reservations', ['user_id'], unique=False)
    op.create_table('user_credit_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance - reserved >= 0', name='chk_available_balance'),
    sa.CheckConstraint('reserved >= 0', name='chk_positive_reserved'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credit_accounts')
    op.drop_index(op.f('ix_credit_reservations_user_id'), table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_status'), table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_idempotency_key'), table_name='credit_reservations')
    op.drop_table('credit_reservations')
    op.drop_index(op.f('ix_credit_ledgers_user_id'), table_name='credit_ledgers')
    op.drop_index(op.f('ix_credit_ledgers_reference_type'), table_name='credit_ledgers')
    op.drop_index(op.f('ix_credit_ledgers_reference_id'), table_name='credit_ledgers')
    op.drop_index(op.f('ix_credit_ledgers_idempotency_key'), table_name='credit_ledgers')
    op.drop_index(op.f('ix_credit_ledgers_created_at'), table_name='credit_ledgers')
    op.drop_table('credit_ledgers')
    credit_reservation_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
