"""add resume task_id field

Revision ID: 45980e8cf4c7
Revises: c68e072f080c
Create Date: 2026-07-19 22:52:22.534745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45980e8cf4c7'
down_revision: Union[str, Sequence[str], None] = 'c68e072f080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_resume_task_id'), 'resume', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_task_id'), table_name='resume')
    op.drop_column('resume', 'task_id')
    # ### end Alembic commands ###
