"""add analysis_bookmarks table

Revision ID: 55cd0e7fc5c1
Revises: a2f39c2f06e2
Create Date: 2026-07-10 15:29:53.188649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cd0e7fc5c1'
down_revision: Union[str, Sequence[str], None] = 'a2f39c2f06e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.Enum('individual', 'comprehensive', 'keyword', name='analysistype'), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_bookmarks_analysis_id'), 'analysis_bookmarks', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_bookmarks_analysis_id'), table_name='analysis_bookmarks')
    op.drop_table('analysis_bookmarks')
    # ### end Alembic commands ###
