"""add title field to comprehensive, keyword analysis

Revision ID: 64f5b0f6240c
Revises: 55cd0e7fc5c1
Create Date: 2026-07-18 00:30:11.130598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64f5b0f6240c'
down_revision: Union[str, Sequence[str], None] = '55cd0e7fc5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comprehensive_analyses', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('keyword_analyses', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE comprehensive_analyses SET title = 'Untitled' WHERE title IS NULL")
    op.execute("UPDATE keyword_analyses SET title = 'Untitled' WHERE title IS NULL")
    op.alter_column('comprehensive_analyses', 'title', nullable=False)
    op.alter_column('keyword_analyses', 'title', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_analyses', 'title')
    op.drop_column('comprehensive_analyses', 'title')
    # ### end Alembic commands ###
