"""add feedback_responses table

Revision ID: 65d8358741aa
Revises: 274313a4d219
Create Date: 2026-08-03 22:54:00.807477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '65d8358741aa'
down_revision: Union[str, Sequence[str], None] = '274313a4d219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_source', sa.Enum('analysis_completed', 'experience_threshold', name='feedbacktriggersource'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_feedback_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campaign_id', name='uq_feedback_user_campaign')
    )
    op.create_index(op.f('ix_feedback_responses_user_id'), 'feedback_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_responses_user_id'), table_name='feedback_responses')
    op.drop_table('feedback_responses')
    sa.Enum(name='feedbacktriggersource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
