"""add status field to resume table

Revision ID: 7f783906eb8c
Revises: 26271fa5752d
Create Date: 2026-07-18 02:58:27.802079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f783906eb8c'
down_revision: Union[str, Sequence[str], None] = '26271fa5752d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    analysisstatus = sa.Enum('PENDING', 'QUEUED', 'SUCCESS', 'FAILED', name='analysisstatus')
    analysisstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('resume', sa.Column('status', analysisstatus, nullable=False, server_default='QUEUED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'status')
    sa.Enum(name='analysisstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
