"""initial

Revision ID: a874fbb5bcf8
Revises: 
Create Date: 2026-06-09 01:23:57.096117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'a874fbb5bcf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('comprehensive_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SUCCESS', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('experience_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comprehensive_analyses_task_id'), 'comprehensive_analyses', ['task_id'], unique=False)
    op.create_index(op.f('ix_comprehensive_analyses_user_id'), 'comprehensive_analyses', ['user_id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SUCCESS', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_analyses_task_id'), 'keyword_analyses', ['task_id'], unique=False)
    op.create_index(op.f('ix_keyword_analyses_user_id'), 'keyword_analyses', ['user_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', name='oauthproviderid'), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_table('presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocks', sa.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('iat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next', sa.Uuid(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_jti_hash'), 'tokens', ['jti_hash'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth', sa.Date(), nullable=False),
    sa.Column('affiliation', sa.Enum('STUDENT', 'EMPLOYED', 'JOBSEEKER', 'OTHER', name='affiliation'), nullable=False),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('desiredRole', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affiliationDetail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('worry', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('interest', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('individual_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SUCCESS', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_analyses_task_id'), 'individual_analyses', ['task_id'], unique=False)
    op.create_index(op.f('ix_individual_analyses_user_id'), 'individual_analyses', ['user_id'], unique=False)
    op.create_table('libraries-experiences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('library_id', 'experience_id')
    )
    op.create_index(op.f('ix_libraries-experiences_user_id'), 'libraries-experiences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_libraries-experiences_user_id'), table_name='libraries-experiences')
    op.drop_table('libraries-experiences')
    op.drop_index(op.f('ix_individual_analyses_user_id'), table_name='individual_analyses')
    op.drop_index(op.f('ix_individual_analyses_task_id'), table_name='individual_analyses')
    op.drop_table('individual_analyses')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tokens_jti_hash'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_table('presets')
    op.drop_table('oauth_accounts')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_keyword_analyses_user_id'), table_name='keyword_analyses')
    op.drop_index(op.f('ix_keyword_analyses_task_id'), table_name='keyword_analyses')
    op.drop_table('keyword_analyses')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_comprehensive_analyses_user_id'), table_name='comprehensive_analyses')
    op.drop_index(op.f('ix_comprehensive_analyses_task_id'), table_name='comprehensive_analyses')
    op.drop_table('comprehensive_analyses')
    op.drop_table('users')
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
