"""use AuditAction enum in audit_logs table

Revision ID: ad21537d92b1
Revises: eabcb62c8a4b
Create Date: 2026-08-03 10:02:56.966322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad21537d92b1'
down_revision: Union[str, Sequence[str], None] = 'eabcb62c8a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audit_action = sa.Enum('CUSTOMER_LIST', 'CUSTOMER_VIEW', name='auditaction')
    audit_action.create(op.get_bind(), checkfirst=True)
    op.alter_column(
        'audit_logs', 'action',
        existing_type=sa.VARCHAR(length=100),
        type_=audit_action,
        existing_nullable=False,
        postgresql_using="action::auditaction",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'audit_logs', 'action',
        existing_type=sa.Enum('CUSTOMER_LIST', 'CUSTOMER_VIEW', name='auditaction'),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
        postgresql_using="action::text",
    )
    sa.Enum(name='auditaction').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
