"""add resume experience_ids field

Revision ID: b66125955ea1
Revises: 033b0fc97894
Create Date: 2026-08-01 12:48:59.105663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66125955ea1'
down_revision: Union[str, Sequence[str], None] = '033b0fc97894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('experience_ids', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'experience_ids')
    # ### end Alembic commands ###
