"""backfill comprehensive_analyses.title, keyword_analyses.title, resume.title/status/language

Revision ID: c930921c5a6c
Revises: 45980e8cf4c7
Create Date: 2026-07-19 23:24:50.392442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c930921c5a6c'
down_revision: Union[str, Sequence[str], None] = '45980e8cf4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE comprehensive_analyses ca
        SET title = COALESCE(
          NULLIF((
            SELECT CASE
              WHEN array_length(ca.experience_ids, 1) = 1
                THEN NULLIF(e.content->>'title', '') || ' 분석'
              ELSE NULLIF(e.content->>'title', '') || ' 등 '
                   || array_length(ca.experience_ids, 1) || '개 분석'
            END
            FROM experiences e
            WHERE e.id = ca.experience_ids[1]
          ), ''),
          to_char(ca.created_at, 'YYYY-MM-DD') || ' 종합 분석'
        )
        """
    )

    # --- keyword_analyses.title / target ---
    op.execute(
        """
        UPDATE keyword_analyses
        SET title = CASE
          WHEN array_length(keywords, 1) IS NULL OR array_length(keywords, 1) = 0
            THEN to_char(created_at, 'YYYY-MM-DD') || ' 키워드 분석'
          WHEN array_length(keywords, 1) <= 3
            THEN array_to_string(keywords, ', ') || ' 분석'
          ELSE array_to_string(keywords[1:3], ', ') || ' 외 '
               || (array_length(keywords, 1) - 3) || '개 분석'
        END,
            target = ''
        """
    )

    # --- resume.title / status / language ---
    # status is inferred from whether a result was ever persisted:
    # result IS NOT NULL -> SUCCESS, result IS NULL -> FAILED
    op.execute(
        """
        UPDATE resume
        SET title    = to_char(created_at, 'YYYY-MM-DD') || ' resume',
            status    = (CASE WHEN result IS NOT NULL THEN 'SUCCESS' ELSE 'FAILED' END)::analysisstatus,
            language = COALESCE(NULLIF(result->'meta'->>'language', ''), 'ko')::language
        """
    )

    # --- clamp generated titles to server-side max length (100 chars) ---
    # Postgres length() counts code points, matching the server's validation unit.
    op.execute(
        """
        UPDATE comprehensive_analyses SET title = left(title, 100) WHERE length(title) > 100
        """
    )
    op.execute(
        """
        UPDATE keyword_analyses SET title = left(title, 100) WHERE length(title) > 100
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
