"""add cover_letters table

Revision ID: d71b5433380f
Revises: b66125955ea1
Create Date: 2026-08-02 21:23:06.762748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd71b5433380f'
down_revision: Union[str, Sequence[str], None] = 'b66125955ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

analysis_status_enum = postgresql.ENUM(
    'PENDING', 'QUEUED', 'SUCCESS', 'FAILED',
    name='analysisstatus',
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', analysis_status_enum, nullable=False),
    sa.Column('target_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_job', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cover_letters_task_id'), 'cover_letters', ['task_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_task_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    # ### end Alembic commands ###
