"""add target field to keyword analysis

Revision ID: f2745010aa55
Revises: 64f5b0f6240c
Create Date: 2026-07-18 00:41:27.617721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2745010aa55'
down_revision: Union[str, Sequence[str], None] = '64f5b0f6240c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword_analyses', sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE keyword_analyses SET target = 'None' WHERE target IS NULL")
    op.alter_column('keyword_analyses', 'target', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_analyses', 'target')
    # ### end Alembic commands ###
