ACCESS_TOKEN_EXPIRE  = 15 # minutes
REFRESH_TOKEN_EXPIRE = 14 # days
JWT_ALG = "HS256"
VERIFICATION_CODE_EXPIRE = 10 # minutes
VERIFICATION_MAX_ATTEMPTS = 5
SHOW_REMAINING_VERIFICATION_ATTEMPTS = False # boolean
ACCESS_TOKEN_KEY = "accessToken"
REFRESH_TOKEN_KEY = "refreshToken"
LOGIN_REDIRECT_ENDPOINT_PREFIX = "/callback/"

# Retry limits
LOGIN_MAX_RETRY_COUNT = 5
LOGIN_RETRY_COOLDOWN = 10 # minutes
VERIFY_EMAIL_MAX_RETRY_COUNT = 5
VERIFY_EMAIL_RETRY_COOLDOWN = 10 # minutes

# File upload
EXPIRES_IN = 300 # seconds