ACCESS_TOKEN_EXPIRE  = 15 # minutes
REFRESH_TOKEN_EXPIRE = 14 # days
JWT_ALG = "HS256"
VERIFICATION_CODE_EXPIRE = 10 # minutes
ACCESS_TOKEN_KEY = "accessToken"
REFRESH_TOKEN_KEY = "refreshToken"
LOGIN_REDIRECT_ENDPOINT_PREFIX = "/callback/"
ENVIRONMENT_KEY = "ENVIRONMENT"