import enum

class UserStatus(str, enum.Enum):
    UNVERIFIED = "unverified"
    VERIFIED = "verified"

class JWTTokenStatus(str, enum.Enum):
    EXPIRED = "AUTH_TOKEN_EXPIRED"
    INVALID = "AUTH_TOKEN_INVALID"
    REUSED = "AUTH_REUSE_DETECTED"
    REVOKED = "AUTH_REVOKED"

class OauthProviderId(str, enum.Enum):
    GOOGLE = "google"

class ErrorResponseCode(str, enum.Enum):
    SERVER_ERROR = "SERVER_ERROR"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    ALREADY_VERIFIED = "ALREADY_VERIFIED"
    INVALID_CODE = "INVALID_CODE"
    SOCIAL_AUTH_FAILED = "SOCIAL_AUTH_FAILED"
    CORS_NOT_ALLOWED = "CORS_NOT_ALLOWED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_MISSING_COOKIES = "AUTH_MISSING_COOKIES"
    AUTH_REUSE_DETECTED = "AUTH_REUSE_DETECTED"
    AUTH_REVOKED = "AUTH_REVOKED"
    DUPLICATE_ONBOARDING = "DUPLICATE_ONBOARDING"
    NOT_FOUND = "NOT_FOUND"
    RESOURCE_NOT_ALLOWED = "RESOURCE_NOT_ALLOWED"
    BAD_REQUEST = "BAD_REQUEST"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_DELETED = "ACCOUNT_DELETED"
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS"
    CODE_EXPIRED = "CODE_EXPIRED"
    CONSENT_MISSING = "CONSENT_MISSING"
    METADATA_ERROR = "METADATA_ERROR"
    FILE_NOT_CONFIRMED = "FILE_NOT_CONFIRMED"

class AnalysisStatus(str, enum.Enum):
    PENDING = "pending"
    QUEUED = "queued"
    SUCCESS = "success"
    FAILED = "failed"

class Affiliation(str, enum.Enum):
    STUDENT = "student"
    EMPLOYED = "employed"
    JOBSEEKER = "jobseeker"
    OTHER = "other"

class AnalysisType(str, enum.Enum):
    individual = "individual"
    comprehensive = "comprehensive"
    keyword = "keyword"