import enum

class UserStatus(str, enum.Enum):
    UNVERIFIED = "unverified"
    VERIFIED = "verified"

class JWTTokenStatus(str, enum.Enum):
    EXPIRED = "AUTH_TOKEN_EXPIRED"
    INVALID = "AUTH_TOKEN_INVALID"
    REUSED = "AUTH_REUSE_DETECTED"
    REVOKED = "AUTH_REVOKED"

class OauthProviderId(str, enum.Enum):
    GOOGLE = "google"

class ErrorResponseCode(str, enum.Enum):
    SERVER_ERROR = "SERVER_ERROR"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    ALREADY_VERIFIED = "ALREADY_VERIFIED"
    INVALID_CODE = "INVALID_CODE"
    SOCIAL_AUTH_FAILED = "SOCIAL_AUTH_FAILED"
    CORS_NOT_ALLOWED = "CORS_NOT_ALLOWED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_MISSING_COOKIES = "AUTH_MISSING_COOKIES"
    AUTH_REUSE_DETECTED = "AUTH_REUSE_DETECTED"
    AUTH_REVOKED = "AUTH_REVOKED"
    DUPLICATE_ONBOARDING = "DUPLICATE_ONBOARDING"